### ISSUE TITLE
Plugin now don't work afrer last windows update 

### ISSUE THREAD

**Issue by Hazard1us** [Ghawken/IndigoPlugin-WinRemote#4]
2021-10-15 17:24:35,343 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,344 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,344 INFO [0] [1] App - -------------------- Starting IndigoPlugin ------------------------------
2021-10-15 17:24:35,346 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,347 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,347 INFO [0] [1] App - :: System Major Version:			10
2021-10-15 17:24:35,347 INFO [0] [1] App - :: System Version Name:			Microsoft Windows NT 10.0.19043.0
2021-10-15 17:24:35,348 INFO [0] [1] App - :: System OSVersion Platform:		Win32NT
2021-10-15 17:24:35,348 INFO [0] [1] App - :: System OSVersion ServicePack:		
2021-10-15 17:24:35,348 INFO [0] [1] App - :: System OSVersion Build:		19043
2021-10-15 17:24:35,349 INFO [0] [1] App - :: System OSVersion Major:		10
2021-10-15 17:24:35,349 INFO [0] [1] App - :: System OSVersion MajorRevision:	0
2021-10-15 17:24:35,350 INFO [0] [1] App - :: System OSVersion Minor:		0
2021-10-15 17:24:35,350 INFO [0] [1] App - :: System OSVersion MinorRevision:	0
2021-10-15 17:24:35,350 INFO [0] [1] App - :: System OSVersion Revision:		0
2021-10-15 17:24:35,351 INFO [0] [1] App - :: System OSVersion Release Id:		0
2021-10-15 17:24:35,351 INFO [0] [1] App - :: System Windows Version:		Windows 10 Enterprise Version 2009 Build 19043
2021-10-15 17:24:35,366 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,367 INFO [0] [1] App - :: Application Version:			15
2021-10-15 17:24:35,367 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,367 DEBUG [0] [1] App - -------------------- Application 64 bit: True ---------------------------
2021-10-15 17:24:35,368 DEBUG [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:35,368 INFO [0] [1] App - :: Windows 64bit Version:		True
2021-10-15 17:24:35,368 INFO [0] [1] App - -------------------------------------------------------------------------
2021-10-15 17:24:37,078 ERROR [0] [1] App - UnHandled Exception Occured.  Please let developer know and will 'Handle' Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at IndigoPlugin.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at IndigoPlugin.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-10-15 17:46:25,539 DEBUG [0] [1] App - Startup Noted.  Sleeping for 90 seconds

**Comment by Ghawken** [comment]
Wow - sorry obviously missed this.

Seems like is a issue with your windows performance counters:
See here:
https://stackoverflow.com/questions/17980178/cannot-load-counter-name-data-because-an-invalid-index-exception
